version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    expose:
      - "2181"
  
  kafka:
    image: wurstmeister/kafka:latest
    expose:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper
    deploy:
      replicas: 3
      
  admin:
    build: ./kafka-admin
    depends_on: 
      - kafka
    expose: 
      - "8080"
      
  consumer:
    build: ./kafka-consumer
    depends_on: 
      - kafka
    expose: 
      - "8080"
    deploy:
      replicas: 2
      
  producer:
    build: ./kafka-producer
    depends_on: 
      - kafka
    expose: 
      - "8080"
    deploy:
      replicas: 3
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - admin
      - consumer
      - producer
    ports:
      - "8080:8080"